name: Apidoc
on:
  workflow_call:

env:
  SLACK_SEND_EVENTS: '["push", "schedule"]'

jobs:
  build_apidoc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/smillerdev/phpdraft:main
    permissions:
      packages: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Detect API docs
        id: detect
        run: |
          echo "docs=$(find docs/apidoc/ -type d -maxdepth 1 -exec basename {} \; | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - name: Build Frontend API documentation
        if: ${{ contains(steps.detect.outputs.docs, 'frontend') }}
        run: |
          install -d build/apidoc/frontend
          phpdraft --file docs/apidoc/frontend/index.apib \
                   --sort Structures \
                   --openapi build/apidoc/frontend/openapi.json > build/apidoc/frontend/index.html

      - name: Build Backend API documentation
        if: ${{ contains(steps.detect.outputs.docs, 'backend') }}
        run: |
          install -d build/apidoc/backend
          phpdraft --file docs/apidoc/backend/index.apib \
                   --sort Structures \
                   --openapi build/apidoc/backend/openapi.json > build/apidoc/backend/index.html

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: API-documentation
          path: build/apidoc
          if-no-files-found: error
          retention-days: 15

      - name: Post a message in a channel
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() && contains(fromJSON(env.SLACK_SEND_EVENTS), github.event_name) && env.SLACK_WEBHOOK_URL != '' }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*${{ github.repository }} (${{ github.ref_name }})*: Apidoc ${{ job.status }}\nURL: ${{ github.event.pull_request.html_url || format('https://github.com/{0}/commit/{1}', github.repository, github.sha) }}\nWorkflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*${{ github.repository }} (${{ github.ref_name }})*: Apidoc ${{ job.status }}\nURL: ${{ github.event.pull_request.html_url || format('https://github.com/{0}/commit/{1}', github.repository, github.sha) }}\nWorkflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
