name: Apidoc
on:
  workflow_call:

jobs:
  build_apidoc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/smillerdev/phpdraft:main
    permissions:
      packages: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect API docs
        id: detect
        run: echo "docs=$(ls docs/apidoc/ | tr '\n' ' ')" >> "$GITHUB_OUTPUT"

      - name: Build Frontend API documentation
        if: ${{ contains(steps.detect.outputs.docs, 'frontend/') }}
        run: |
          install -d build/apidoc/frontend
          phpdraft -f docs/apidoc/frontend/index.apib -s Structures > build/apidoc/frontend/index.html

      - name: Build Backend API documentation
        if: ${{ contains(steps.detect.outputs.docs, 'backend/') }}
        run: |
          install -d build/apidoc/backend
          phpdraft -f docs/apidoc/backend/index.apib -s Structures > build/apidoc/backend/index.html

      - uses: actions/upload-artifact@v4
        with:
          name: API-documentation
          path: build/apidoc
          if-no-files-found: error
          retention-days: 15
