name: Web CloudFront deploy
on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        default: 'Test'
        required: false
        type: string
      domain:
        description: 'The domain to deploy to'
        default: 'test.web.dap.aero'
        required: false
        type: string
      cloudfront-distribution-id:
        description: 'The ID of the cloudfront distribution'
        required: true
        type: string
      bucket-prefix:
        description: 'The prefix for upload buckets'
        required: true
        type: string
      node-version:
        description: 'Version of node to deploy with'
        default: '20.x'
        required: false
        type: string
      artifact-name:
        description: 'Artifact to deploy'
        default: build-20.x
        required: false
        type: string
    secrets:
      amazon_role:
        description: The AWS role to assume
        required: true
      npm_pat:
        description: The PAT for NPM registry access
        required: true

jobs:
  deploy_cloudfront:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    name: "Deploy to ${{ inputs.environment }} CloudFront"
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://npm.pkg.github.com
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --production=false --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PAT }}

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          merge-multiple: true
          name: ${{ inputs.artifact-name }}
          path: out

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.amazon_role }}

      - name: Deploy website
        env:
          DEPLOY_DISTRIBUTION_ID: "${{ inputs.cloudfront-distribution-id }}"
          DEPLOY_BUCKET_PREFIX: "${{ inputs.bucket-prefix }}"
          SITE_ROOT: "https://${{ inputs.domain }}"
        run: yarn deploy
